require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TicketStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # TicketStatus. As you add validations to TicketStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TicketStatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ticket_statuses as @ticket_statuses" do
      ticket_status = TicketStatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ticket_statuses).should eq([ticket_status])
    end
  end

  describe "GET show" do
    it "assigns the requested ticket_status as @ticket_status" do
      ticket_status = TicketStatus.create! valid_attributes
      get :show, {:id => ticket_status.to_param}, valid_session
      assigns(:ticket_status).should eq(ticket_status)
    end
  end

  describe "GET new" do
    it "assigns a new ticket_status as @ticket_status" do
      get :new, {}, valid_session
      assigns(:ticket_status).should be_a_new(TicketStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket_status as @ticket_status" do
      ticket_status = TicketStatus.create! valid_attributes
      get :edit, {:id => ticket_status.to_param}, valid_session
      assigns(:ticket_status).should eq(ticket_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TicketStatus" do
        expect {
          post :create, {:ticket_status => valid_attributes}, valid_session
        }.to change(TicketStatus, :count).by(1)
      end

      it "assigns a newly created ticket_status as @ticket_status" do
        post :create, {:ticket_status => valid_attributes}, valid_session
        assigns(:ticket_status).should be_a(TicketStatus)
        assigns(:ticket_status).should be_persisted
      end

      it "redirects to the created ticket_status" do
        post :create, {:ticket_status => valid_attributes}, valid_session
        response.should redirect_to(TicketStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_status as @ticket_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketStatus.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_status => { "name" => "invalid value" }}, valid_session
        assigns(:ticket_status).should be_a_new(TicketStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketStatus.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_status" do
        ticket_status = TicketStatus.create! valid_attributes
        # Assuming there are no other ticket_statuses in the database, this
        # specifies that the TicketStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TicketStatus.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => ticket_status.to_param, :ticket_status => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested ticket_status as @ticket_status" do
        ticket_status = TicketStatus.create! valid_attributes
        put :update, {:id => ticket_status.to_param, :ticket_status => valid_attributes}, valid_session
        assigns(:ticket_status).should eq(ticket_status)
      end

      it "redirects to the ticket_status" do
        ticket_status = TicketStatus.create! valid_attributes
        put :update, {:id => ticket_status.to_param, :ticket_status => valid_attributes}, valid_session
        response.should redirect_to(ticket_status)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_status as @ticket_status" do
        ticket_status = TicketStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_status.to_param, :ticket_status => { "name" => "invalid value" }}, valid_session
        assigns(:ticket_status).should eq(ticket_status)
      end

      it "re-renders the 'edit' template" do
        ticket_status = TicketStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_status.to_param, :ticket_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_status" do
      ticket_status = TicketStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => ticket_status.to_param}, valid_session
      }.to change(TicketStatus, :count).by(-1)
    end

    it "redirects to the ticket_statuses list" do
      ticket_status = TicketStatus.create! valid_attributes
      delete :destroy, {:id => ticket_status.to_param}, valid_session
      response.should redirect_to(ticket_statuses_url)
    end
  end

end
